import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const source=await readFile(new URL('vendor/nvidia-nis/NIS_Scaler.h',root),'utf8');
const config=await readFile(new URL('vendor/nvidia-nis/NIS_Config.h',root),'utf8');
function fn(name){const start=source.indexOf(name+'('),brace=source.indexOf('{',start);let end=brace+1,depth=1;while(depth){if(source[end]==='{')depth++;if(source[end]==='}')depth--;end++;}return source.slice(source.lastIndexOf('\n',start)+1,brace).split('#')[0]+source.slice(brace,end);}
function flatten(s,name,size){return s.replace(new RegExp(name+'\\[([^\\]]+)\\]\\[([^\\]]+)\\]','g'),(_,a,b)=>`${name}[(${a})*${size}+(${b})]`);}
let edge=fn('GetEdgeMap').replace('p[4][4]','p[16]');edge=flatten(edge,'p',4);
let interp=fn('GetInterpEdgeMap').replace('edge[2][2]','edge[4]');interp=flatten(interp,'edge',2);
let filters=['CalcLTI','EvalPoly6','FilterNormal','AddDirFilters'].map(fn).join('\n').replaceAll('p[6][6]','p[36]');filters=flatten(filters,'p',6);filters=flatten(flatten(filters,'shCoefScaler',6),'shCoefUSM',6);
function bank(name){const body=config.match(new RegExp('constexpr float '+name+'\\[kPhaseCount\\]\\[kFilterSize\\] = \\{([\\s\\S]*?)\\n    \\};'))?.[1];if(!body)throw Error('Missing coefficient bank '+name);const rows=[...body.matchAll(/\{([^}]+)\}/g)].map(m=>m[1].split(',').slice(0,6).map(v=>v.trim().replace(/f$/,'')));if(rows.length!==64)throw Error('NIS phase count changed');return rows.flat().join(',');}
const license=source.slice(0,source.indexOf('//---------------------------------------------------------------------------------'));
let shader=`#version 300 es
${license}
precision highp float;
precision highp int;
uniform sampler2D image;
uniform vec2 outputSize;
out vec4 color;
#define NVF float
#define NVF4 vec4
#define NVI int
#define NVB bool
#define NIS_UNROLL
#define NIS_UNROLL_INNER
#define NIS_SCALE_FLOAT 1.0
#define kPhaseCount 64
#define saturate(x) clamp(x,0.0,1.0)
#define lerp mix
const float kDetectRatio=2.201171875,kDetectThres=0.0625,kMinContrastRatio=2.0,kRatioNorm=0.125,kContrastBoost=1.0,kEps=1.0/255.0;
// NVIDIA SDR configuration for a restrained 0.25 sharpness setting.
const float kSharpStartY=0.45,kSharpScaleY=1.0/0.45,kSharpStrengthMin=0.1,kSharpStrengthScale=0.7125,kSharpLimitMin=0.1,kSharpLimitScale=0.25;
const float shCoefScaler[384]=float[384](${bank('coef_scale')});
const float shCoefUSM[384]=float[384](${bank('coef_usm')});
${edge.replace(/\bconst /g,'')}\n${interp.replace(/\bconst /g,'')}\n${filters.replace(/\bconst /g,'')}
float luma(vec3 c){return dot(c,vec3(0.2126,0.7152,0.0722));}
void main(){
 vec2 size=vec2(textureSize(image,0));
 vec2 dst=vec2(gl_FragCoord.x,outputSize.y-gl_FragCoord.y);
 vec2 src=dst*size/outputSize-0.5,phase=fract(src);
 ivec2 base=ivec2(floor(src));float p[36];float e[16];
 for(int y=0;y<6;y++)for(int x=0;x<6;x++)p[y*6+x]=luma(texelFetch(image,clamp(base+ivec2(x-2,y-2),ivec2(0),ivec2(size)-1),0).rgb);
 for(int y=0;y<4;y++)for(int x=0;x<4;x++)e[y*4+x]=p[(y+1)*6+x+1];
 vec4 edges[4];for(int y=0;y<2;y++)for(int x=0;x<2;x++)edges[y*2+x]=GetEdgeMap(e,y,x);
 vec4 w=GetInterpEdgeMap(edges,phase.x,phase.y);
 int px=int(phase.x*64.0),py=int(phase.y*64.0);
 float Y=FilterNormal(p,px,py)*(1.0-dot(w,vec4(1)))+AddDirFilters(p,phase.x,phase.y,px,py,w);
 vec3 rgb=texture(image,(src+0.5)/size).rgb;
 color=vec4(clamp(rgb+vec3(Y-luma(rgb)),0.0,1.0),1.0);
}`;
shader=shader.replace(/(\d(?:[\d.]*))f\b/g,'$1');
// GLSL ES does not implicitly convert integer literals in float expressions.
shader=shader.replace(/(NVF \w+ = )0;/g,'$10.0;').replace('g_0_90_max + g_45_135_max == 0','g_0_90_max + g_45_135_max == 0.0')
 .replace(/(pphase_p(?:45|135)) >= 1/g,'$1 >= 1.0').replace(/(pphase_p(?:45|135)) - 1/g,'$1 - 1.0')
 .replace(/(pphase_p(?:45|135)) \* 64/g,'$1 * 64.0').replace('= 1 + (phase_x_frac','= 1.0 + (phase_x_frac');
await writeFile(new URL('src/nis-fragment.js',root),'// Generated by tools/build-nis.mjs from NVIDIA NIS 1.0.3.\nexport default '+JSON.stringify(shader)+';\n');
